name: test
on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 * * *'
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: install
      run: |
        pwd 
        ls -al

        wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -f
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: python test
      run: |
        python3 wh.py